"""Register the memU bridging task with cron on macOS/Linux.

The Unix guides used to have the agent paste the ~1.2 KB pipeline prompt inline
into a crontab entry. macOS cron truncates crontab lines around 1 KB, so every
tick died mid-quote before the agent binary ever started (memU#591) — the Unix
sibling of the Windows ``schtasks /TR`` wall (memU#539). This backend is the
same fix the Windows helper shipped in #546, ported: the prompt lives in
``bridge-prompt.txt``, a short generated ``bridge.sh`` reads it (with a
single-instance lock and its ``PATH`` baked in, so the crontab needs no env
lines), and the crontab entry invokes only the script.

``install`` also migrates: any pre-existing entry for this host — a previous
helper install or a legacy hand-pasted inline entry — is replaced, never
duplicated. launchd is deliberately out of scope; cron is the default the
guides register on macOS too, and launchd users keep the doc-driven path.

Unix-only: every entry point raises on Windows, mirroring ``windows.py``.
"""

from __future__ import annotations

import platform
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from memu.hosts.scheduling.prompt import bridging_pipeline_prompt

# The auth/resolution gates are platform-neutral (plain subprocess probes) and
# live in windows.py only because it shipped first; shared here, not duplicated.
from memu.hosts.scheduling.windows import _agent_binary, _auth_gate, _resolve_agent

if TYPE_CHECKING:
    from memu.hosts.bridging import Layout
    from memu.hosts.host_cli import HostSpec

DEFAULT_INTERVAL_MINUTES = 60

SCRIPT_NAME = "bridge.sh"
PROMPT_NAME = "bridge-prompt.txt"
LOG_NAME = "bridge.log"

# The marker every legacy hand-pasted inline entry carries (the prompt's own
# opening words). Scoped with the host's tree below so one host's uninstall
# never eats another's entry.
_LEGACY_MARKER = "memU bridging pipeline"


# ---------------------------------------------------------------------------
# Pure builders — no I/O, no platform gate; unit-tested on any OS.
# ---------------------------------------------------------------------------


def cron_expression(interval_minutes: int) -> str:
    """The schedule field: hourly at :00 by default, ``*/N`` for sub-hourly."""
    if interval_minutes == 60:
        return "0 * * * *"
    if 1 <= interval_minutes < 60:
        return f"*/{interval_minutes} * * * *"
    msg = f"--interval must be 1-60 minutes for cron (got {interval_minutes})"
    raise ValueError(msg)


def shell_invocation(agent_path: str, schedule_command: str) -> str:
    """The script's agent call, e.g. ``'/usr/local/bin/claude' -p "$prompt"``.

    ``$prompt`` holds the prompt file's contents; quoting it passes the long
    text as one argument, so nothing long ever sits on a command line the
    scheduler parses — the same shape as the PowerShell wrapper.
    """
    tokens = schedule_command.split()
    if not tokens:
        msg = "schedule_command is empty"
        raise ValueError(msg)
    rest = ['"$prompt"' if t == "{prompt}" else t for t in tokens[1:]]
    return " ".join([shlex.quote(agent_path), *rest])


def bridge_script(agent_path: str, schedule_command: str, base: Path, path_dirs: list[str]) -> str:
    """The POSIX sh wrapper the crontab entry runs.

    ``PATH`` is baked in rather than written as a crontab env line — crontab
    env lines are file-global and would leak into the user's other entries.
    ``cd`` into the host tree so a workspace-trust flag in the template
    (``cursor-agent --trust``) grants trust to memU's own tree, never to
    cron's default working directory.
    """
    quoted_base = shlex.quote(str(base))
    path_prefix = shlex.quote(":".join(path_dirs) + ":")
    return "\n".join([
        "#!/bin/sh",
        "# memU bridging wrapper (generated by `schedule install`; do not edit -",
        "# re-run install to regenerate).",
        f"# The pipeline prompt lives in {PROMPT_NAME} because cron truncates",
        "# crontab lines around 1 KB (memU#591); the crontab entry runs only this script.",
        f'PATH={path_prefix}"$PATH"; export PATH',
        f"DIR={quoted_base}",
        "# Single-instance lock: a tick can fire while a long backlog run is still",
        "# going; a second run would race it on jobs/ and double-commit. mkdir is",
        "# atomic; a stale lock older than 3h is reclaimed. Tradeoff: a legitimate",
        "# run longer than 3h loses its lock to the next tick and can double-run -",
        "# accepted deliberately, because the alternative (no reclaim) lets one",
        '# crashed run wedge the schedule forever. Do not "fix" one side without',
        "# weighing the other.",
        'LOCK="$DIR/.bridge.lock"',
        'if ! mkdir "$LOCK" 2>/dev/null; then',
        '  if [ -n "$(find "$LOCK" -maxdepth 0 -mmin +180 2>/dev/null)" ]; then',
        '    rmdir "$LOCK" 2>/dev/null',
        '    mkdir "$LOCK" 2>/dev/null || exit 0',
        "  else",
        '    echo "$(date \'+%F %T\') skipped: another bridging run is in progress" >> "$DIR/' + LOG_NAME + '"',
        "    exit 0",
        "  fi",
        "fi",
        "trap 'rmdir \"$LOCK\" 2>/dev/null' EXIT INT TERM",
        'cd "$DIR" || exit 1',
        f'prompt=$(cat "$DIR/{PROMPT_NAME}")',
        f'{shell_invocation(agent_path, schedule_command)} >> "$DIR/{LOG_NAME}" 2>&1',
        "",
    ])


def cron_entry(script: Path, interval_minutes: int) -> str:
    """The one short crontab line — the whole point (memU#591)."""
    return f"{cron_expression(interval_minutes)} {shlex.quote(str(script))}"


def is_host_entry(line: str, layout: Layout) -> bool:
    """Does this crontab line belong to this host's bridging task?

    Matches both layouts: the helper's ``bridge.sh`` entry, and a legacy
    hand-pasted inline entry (recognized by the prompt marker plus this host's
    working tree, which the inline prompt always names). Comments and other
    hosts' entries never match.
    """
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return False
    if str(layout.base / SCRIPT_NAME) in line or f"hosts/{layout.host}/{SCRIPT_NAME}" in line:
        return True
    return _LEGACY_MARKER in line and f"hosts/{layout.host}/" in line


# ---------------------------------------------------------------------------
# Execution — Unix-only.
# ---------------------------------------------------------------------------


def _require_unix() -> None:
    if platform.system() == "Windows":
        msg = "the cron backend is only usable on macOS/Linux; Windows uses the Task Scheduler backend"
        raise RuntimeError(msg)


def _read_crontab() -> str:
    # A missing crontab exits non-zero ("no crontab for <user>") — that is the
    # empty starting state, not an error.
    proc = subprocess.run(["crontab", "-l"], capture_output=True, text=True)  # noqa: S607
    return proc.stdout if proc.returncode == 0 else ""


def _write_crontab(text: str) -> tuple[bool, str]:
    proc = subprocess.run(["crontab", "-"], input=text, capture_output=True, text=True)  # noqa: S607
    return proc.returncode == 0, proc.stderr.strip()


def _paths(layout: Layout) -> tuple[Path, Path, Path]:
    return layout.base / SCRIPT_NAME, layout.base / PROMPT_NAME, layout.base / LOG_NAME


def install(spec: HostSpec, layout: Layout, *, interval_minutes: int = DEFAULT_INTERVAL_MINUTES) -> int:
    """Write the prompt file + wrapper and register the crontab entry."""
    _require_unix()
    try:
        entry_expr = cron_expression(interval_minutes)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    agent_path = _resolve_agent(spec)
    if agent_path is None:
        hint = spec.install_hint or "  Install a standalone CLI a bare process can find."
        print(
            f"error: `{_agent_binary(spec)}` is not on PATH — the scheduled run needs a standalone CLI "
            f"(memU#538 Symptom A).\n{hint}\n  Then re-run `{spec.binary} schedule install`.",
            file=sys.stderr,
        )
        return 1
    layout.base.mkdir(parents=True, exist_ok=True)
    if (rc := _auth_gate(spec, agent_path, layout.base)) != 0:
        return rc

    script, prompt_file, _log = _paths(layout)
    prompt_file.write_text(bridging_pipeline_prompt(spec), encoding="utf-8")
    path_dirs = [str(Path(agent_path).parent)]
    if (memu_path := shutil.which(spec.binary)) is not None and str(Path(memu_path).parent) not in path_dirs:
        path_dirs.append(str(Path(memu_path).parent))
    script.write_text(bridge_script(agent_path, spec.schedule_command, layout.base, path_dirs), encoding="utf-8")
    script.chmod(0o755)

    # Replace, never duplicate: drop this host's previous entries — including a
    # legacy inline one, which this install migrates — and append the new line.
    kept = [line for line in _read_crontab().splitlines() if not is_host_entry(line, layout)]
    kept.append(cron_entry(script, interval_minutes))
    ok, err = _write_crontab("\n".join(kept) + "\n")
    if not ok:
        print(f"error: could not write the crontab: {err}", file=sys.stderr)
        return 1
    print(f"registered a cron entry ({entry_expr}) running {script}")
    print(f"  verify it can actually run:  {spec.binary} schedule verify")
    return 0


def uninstall(spec: HostSpec, layout: Layout) -> int:
    """Remove this host's crontab entry (either layout) and generated files."""
    _require_unix()
    lines = _read_crontab().splitlines()
    kept = [line for line in lines if not is_host_entry(line, layout)]
    if len(kept) != len(lines):
        ok, err = _write_crontab("\n".join(kept) + ("\n" if kept else ""))
        if not ok:
            print(f"error: could not write the crontab: {err}", file=sys.stderr)
            return 1
        print(f"removed {len(lines) - len(kept)} crontab entr(y/ies) for {spec.display} bridging")
    else:
        # Idempotent: an absent entry is a warning, not a failure.
        print(f"warning: no {spec.display} bridging entry found in the crontab", file=sys.stderr)

    script, prompt_file, _log = _paths(layout)
    for artifact in (script, prompt_file):
        artifact.unlink(missing_ok=True)
    print(f"  (kept the run log {layout.base / LOG_NAME} if present)")
    return 0


def status(spec: HostSpec, layout: Layout) -> int:
    """Print the registered entry, the lock state, and the log tail."""
    _require_unix()
    entries = [line for line in _read_crontab().splitlines() if is_host_entry(line, layout)]
    if not entries:
        print(f"not registered (run `{spec.binary} schedule install`)")
        return 0
    for line in entries:
        print(f"crontab: {line}")
    lock = layout.base / ".bridge.lock"
    print(f"lock:    {'held (a run is in progress)' if lock.exists() else 'free'}")
    log = layout.base / LOG_NAME
    if log.exists():
        tail = log.read_text(encoding="utf-8", errors="replace").splitlines()[-3:]
        for line in tail:
            print(f"log:     {line}")
    return 0


def verify(spec: HostSpec, layout: Layout) -> int:
    """Prove the entry can actually run — registered, sane files, agent authenticates.

    Deliberately does not trigger a full pipeline run (that would memorize real
    sessions as a side effect); mirrors the Windows ``verify``, then points at the
    filesystem traces to watch after the next real tick.
    """
    _require_unix()
    entries = [line for line in _read_crontab().splitlines() if is_host_entry(line, layout)]
    if not entries:
        print(f"not registered (run `{spec.binary} schedule install`)", file=sys.stderr)
        return 1
    script, prompt_file, _log = _paths(layout)
    problems = []
    if not script.exists():
        problems.append(f"{script} is missing")
    elif not script.stat().st_mode & 0o111:
        problems.append(f"{script} is not executable")
    if not prompt_file.exists():
        problems.append(f"{prompt_file} is missing")
    elif prompt_file.read_text(encoding="utf-8").strip() != bridging_pipeline_prompt(spec):
        problems.append(f"{prompt_file} has drifted from the canonical prompt")
    if problems:
        for problem in problems:
            print(f"error: {problem} — re-run `{spec.binary} schedule install`", file=sys.stderr)
        return 1

    agent_path = _resolve_agent(spec)
    if agent_path is None:
        print(f"error: `{_agent_binary(spec)}` is no longer on PATH (memU#538 Symptom A)", file=sys.stderr)
        return 1
    if (rc := _auth_gate(spec, agent_path, layout.base)) != 0:
        return rc

    print(f"ok: the cron entry is registered and `{_agent_binary(spec)}` authenticates headless")
    print(
        "  after the next scheduled run, confirm it did work by traces, not its summary:\n"
        f"    - {layout.jobs} timestamps advanced,\n"
        f"    - {layout.session_manifest} moved, and\n"
        f"    - {layout.base / LOG_NAME} grew"
    )
    return 0
