r"""Register the memU bridging task with Windows Task Scheduler.

Unix hosts schedule bridging by pasting the pipeline prompt into a crontab or a
launchd plist (see each host's ``BRIDGING_TASK.md``). Windows can't take that
path — Task Scheduler's ``schtasks /TR`` re-parses the ~1000-character quoted
prompt and dies on the spaces (memU#539), and a bare scheduled process can't find
a desktop-only ``claude`` (memU#538). This backend sidesteps both: it writes the
prompt to a file and a small PowerShell wrapper that reads it, then registers a
Task Scheduler entry that runs *only* the wrapper, under a canonical task name.

Prior art: **jshchnz/claude-code-scheduler** — the established (500+ star) Claude
Code scheduler, with per-OS backends over schtasks/launchd/cron and every task
namespaced under a scheduler folder (``\ClaudeScheduler\<id>``; ours is the same
shape, ``\memU\<name>``, so uninstall is deterministic). We diverge for the
bridging case: ``Register-ScheduledTask`` under an S4U principal, so the run is
windowless and works while logged out, plus the prompt-file indirection below
because the pipeline prompt is too long to sit on the command line.

Windows-only: every entry point raises on other platforms. Nothing here touches
the cron or launchd code paths, so their long-standing behavior is unchanged.
"""

from __future__ import annotations

import json
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from memu.hosts.scheduling.prompt import bridging_pipeline_prompt

if TYPE_CHECKING:
    from memu.hosts.bridging import Layout
    from memu.hosts.host_cli import HostSpec

# Task Scheduler folder that namespaces every memU task, so `\memU\<name>` never
# collides with an unrelated task and a whole-folder query lists only ours.
TASK_PATH = "\\memU\\"
DEFAULT_INTERVAL_MINUTES = 60

WRAPPER_NAME = "memu-bridge.ps1"
PROMPT_NAME = "bridge-prompt.txt"
LOG_NAME = "bridge.log"


# ---------------------------------------------------------------------------
# Pure builders — no I/O, no platform gate; unit-tested on any OS.
# ---------------------------------------------------------------------------


def _invocation_args(schedule_command: str) -> list[str]:
    """The agent's arguments after the binary, with ``{prompt}`` still a token.

    ``schedule_command`` is ``claude -p {prompt}`` / ``codex exec {prompt}``; the
    first token is the binary (resolved separately to an absolute path) and the
    ``{prompt}`` placeholder must stand alone so it maps cleanly to one argument.
    """
    tokens = schedule_command.split()
    if not tokens:
        msg = "schedule_command is empty"
        raise ValueError(msg)
    return tokens[1:]


def powershell_invocation(agent_path: str, schedule_command: str) -> str:
    """The wrapper's agent call, e.g. ``& 'C:\\...\\claude.exe' -p $prompt``.

    ``$prompt`` is the wrapper variable holding the prompt file's contents, so the
    long text is passed as one argument by PowerShell and never touches a shell
    that would split it on spaces — the whole point of the file indirection.
    """
    rest = ["$prompt" if t == "{prompt}" else t for t in _invocation_args(schedule_command)]
    return " ".join([f"& '{agent_path}'", *rest])


def agent_check_argv(agent_path: str, schedule_command: str, prompt: str) -> list[str]:
    """The argv for a headless auth probe, e.g. ``[claude, -p, ping]`` (memU#538)."""
    rest = [prompt if t == "{prompt}" else t for t in _invocation_args(schedule_command)]
    return [agent_path, *rest]


def wrapper_script(
    agent_path: str,
    schedule_command: str,
    prompt_file: Path,
    log_file: Path,
    path_dirs: list[str],
) -> str:
    """The PowerShell wrapper the scheduled task runs.

    It re-establishes ``PATH`` (Task Scheduler does not inherit the interactive
    shell's), reads the prompt from a file, and runs the agent. Absolute paths are
    baked in at install time — the #530 "the scheduler's PATH is not your shell's"
    capture, ported to Windows.
    """
    path_prefix = ";".join(path_dirs)
    return "\n".join([
        "# memU bridging wrapper (generated by `schedule install`; do not edit -",
        "# re-run install to regenerate). Prior art: jshchnz/claude-code-scheduler.",
        "$ErrorActionPreference = 'Stop'",
        f"$env:Path = '{path_prefix};' + $env:Path",
        f"$prompt = Get-Content -Raw -Encoding UTF8 -LiteralPath '{prompt_file}'",
        f"{powershell_invocation(agent_path, schedule_command)} *>> '{log_file}'",
        "exit $LASTEXITCODE",
        "",
    ])


def register_script(task_name: str, wrapper_path: Path, interval_minutes: int) -> str:
    """PowerShell that registers the task.

    - ``-LogonType S4U``: runs whether or not the user is logged on, with no stored
      password, and — running in session 0 — windowless, so no console flashes each
      run (a schtasks-based approach needs a hidden-VBS or ``-WindowStyle Hidden``
      shim for this; the principal gives it to us for free).
    - ``-RunLevel Limited``: bridging is not an admin job; elevating could read a
      different profile's credentials.
    - ``-StartWhenAvailable``: catch up a run missed while the machine was off.
    - ``-RepetitionInterval`` off a ``-Once`` trigger: the robust way to say "every
      N minutes forever" on Win10/11.
    """
    arg = f'-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{wrapper_path}"'
    return "\n".join([
        f"$action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument '{arg}'",
        "$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date "
        f"-RepetitionInterval (New-TimeSpan -Minutes {interval_minutes})",
        "$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType S4U -RunLevel Limited",
        "$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -MultipleInstances IgnoreNew "
        "-AllowStartIfOnBatteries -DontStopIfGoingOnBatteries",
        f"Register-ScheduledTask -TaskName '{task_name}' -TaskPath '{TASK_PATH}' "
        "-Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null",
    ])


def unregister_script(task_name: str) -> str:
    return f"Unregister-ScheduledTask -TaskName '{task_name}' -TaskPath '{TASK_PATH}' -Confirm:$false"


def status_script(task_name: str) -> str:
    return (
        f"Get-ScheduledTaskInfo -TaskName '{task_name}' -TaskPath '{TASK_PATH}' | "
        "Format-List TaskName, LastRunTime, LastTaskResult, NextRunTime"
    )


# ---------------------------------------------------------------------------
# Execution — Windows-only.
# ---------------------------------------------------------------------------


def _require_windows() -> None:
    if platform.system() != "Windows":
        msg = "the Windows Task Scheduler backend is only usable on Windows"
        raise RuntimeError(msg)


def _run_powershell(script: str) -> subprocess.CompletedProcess[str]:
    # powershell.exe is a fixed Windows system binary (resolved from System32) and
    # `script` is generated here, never user input — the bandit process checks don't apply.
    argv = ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", script]
    return subprocess.run(argv, capture_output=True, text=True)  # noqa: S603


def _agent_binary(spec: HostSpec) -> str:
    return spec.schedule_command.split()[0]


def _resolve_agent(spec: HostSpec) -> str | None:
    """Absolute path to the host's agent CLI, or ``None`` if it is not on ``PATH``
    (memU#538 Symptom A — a desktop-only bundle is not a standalone CLI)."""
    return shutil.which(_agent_binary(spec))


def _authenticates(spec: HostSpec, agent_path: str) -> tuple[bool, str]:
    """Does a cold headless run authenticate? (memU#538 Symptom B.)

    Runs the host's own invocation with a trivial prompt. Exit 0 means the CLI has
    a usable headless credential; the failure to catch is "Not logged in · Please
    run /login" (exit 1), where a desktop login exists but the CLI cannot see it.
    """
    argv = agent_check_argv(agent_path, spec.schedule_command, "ping")
    try:
        proc = subprocess.run(argv, capture_output=True, text=True, timeout=120)  # noqa: S603
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    return proc.returncode == 0, (proc.stderr or proc.stdout).strip()


def _paths(layout: Layout) -> tuple[Path, Path, Path, Path]:
    base = layout.base
    return base / WRAPPER_NAME, base / PROMPT_NAME, base / LOG_NAME, base / f".schedule.{layout.host}.json"


def _auth_gate(spec: HostSpec, agent_path: str) -> int:
    """Run the headless-auth check for hosts that need it; 0 = pass, 1 = abort."""
    if not spec.needs_headless_auth:
        return 0
    ok, detail = _authenticates(spec, agent_path)
    if ok:
        return 0
    print(
        f"error: `{_agent_binary(spec)}` resolves but cannot authenticate headless "
        f"({detail or 'no output'}).\n"
        "  The scheduled run has no browser and cannot see any Claude Desktop login. "
        "Give the CLI its own headless credential:\n"
        "    claude setup-token   # -> $CLAUDE_CODE_OAUTH_TOKEN\n"
        "  or set ANTHROPIC_API_KEY, then re-run. (memU#538 Symptom B.)",
        file=sys.stderr,
    )
    return 1


def install(spec: HostSpec, layout: Layout, *, interval_minutes: int = DEFAULT_INTERVAL_MINUTES) -> int:
    """Register the bridging task, gating on a usable standalone CLI first."""
    _require_windows()
    agent_path = _resolve_agent(spec)
    if agent_path is None:
        print(
            f"error: `{_agent_binary(spec)}` is not on PATH.\n"
            f"  {spec.display}'s scheduled run needs a standalone CLI a bare process can find; a "
            "desktop-app bundle does not count (memU#538 Symptom A). Install the standalone CLI "
            "(native installer / winget / npm) and re-run.",
            file=sys.stderr,
        )
        return 1
    if (rc := _auth_gate(spec, agent_path)) != 0:
        return rc

    wrapper, prompt_file, log_file, registry = _paths(layout)
    layout.base.mkdir(parents=True, exist_ok=True)
    prompt_file.write_text(bridging_pipeline_prompt(spec), encoding="utf-8")

    path_dirs = [str(Path(agent_path).parent)]
    if (memu_path := shutil.which(spec.binary)) is not None:
        path_dirs.append(str(Path(memu_path).parent))
    # utf-8-sig: Windows PowerShell 5.1 runs a `-File` script in the ANSI code page
    # unless it sees a BOM, which would mangle a non-ASCII path (e.g. a CJK username)
    # baked into the wrapper. The BOM makes both 5.1 and 7 decode it as UTF-8.
    wrapper.write_text(
        wrapper_script(agent_path, spec.schedule_command, prompt_file, log_file, path_dirs), encoding="utf-8-sig"
    )

    proc = _run_powershell(register_script(spec.task_name, wrapper, interval_minutes))
    if proc.returncode != 0:
        print(f"error: Task Scheduler registration failed: {proc.stderr.strip()}", file=sys.stderr)
        return 1

    registry.write_text(
        json.dumps(
            {"task_name": spec.task_name, "task_path": TASK_PATH, "wrapper": str(wrapper), "prompt": str(prompt_file)},
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"registered '{TASK_PATH}{spec.task_name}' — runs every {interval_minutes} min, hidden, catches up if missed")
    print(f"  wrapper: {wrapper}")
    print(f"  verify it can actually run:  {spec.binary} schedule verify")
    return 0


def uninstall(spec: HostSpec, layout: Layout) -> int:
    """Remove the task by its canonical name and clean up generated artifacts."""
    _require_windows()
    proc = _run_powershell(unregister_script(spec.task_name))
    if proc.returncode == 0:
        print(f"removed '{TASK_PATH}{spec.task_name}'")
    else:
        # Idempotent: an absent task is a warning, not a failure — uninstall should
        # succeed whether or not install ever did.
        print(f"warning: could not remove '{TASK_PATH}{spec.task_name}': {proc.stderr.strip()}", file=sys.stderr)

    wrapper, prompt_file, _log, registry = _paths(layout)
    for artifact in (wrapper, prompt_file, registry):
        artifact.unlink(missing_ok=True)
    print(f"  (kept the run log {layout.base / LOG_NAME} if present)")
    return 0


def status(spec: HostSpec, layout: Layout) -> int:
    """Print whether the task is registered and its last/next run."""
    _require_windows()
    proc = _run_powershell(status_script(spec.task_name))
    if proc.returncode == 0:
        print(proc.stdout.strip())
    else:
        print(f"not registered: '{TASK_PATH}{spec.task_name}' (run `{spec.binary} schedule install`)")
    return 0


def verify(spec: HostSpec, layout: Layout) -> int:
    """Prove the task can actually run — registered, and the agent authenticates.

    Deliberately does not trigger a full pipeline run (that would memorize real
    sessions as a side effect); it checks the two things that silently break the
    record seam, then points at the filesystem traces to watch after the next real
    run — the same "trust traces, not the run's self-report" rule the cron guide uses.
    """
    _require_windows()
    registered = _run_powershell(status_script(spec.task_name)).returncode == 0
    if not registered:
        print(f"not registered: '{TASK_PATH}{spec.task_name}' (run `{spec.binary} schedule install`)", file=sys.stderr)
        return 1

    agent_path = _resolve_agent(spec)
    if agent_path is None:
        print(f"error: `{_agent_binary(spec)}` is no longer on PATH (memU#538 Symptom A)", file=sys.stderr)
        return 1
    if (rc := _auth_gate(spec, agent_path)) != 0:
        return rc

    print(f"ok: '{TASK_PATH}{spec.task_name}' is registered and `{_agent_binary(spec)}` authenticates headless")
    print(
        "  after the next scheduled run, confirm it did work by traces, not its summary:\n"
        f"    - {layout.jobs} timestamps advanced, and\n"
        f"    - {layout.session_manifest} moved"
    )
    return 0
