name: Blank issue
description: Create a new issue from scratch
title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening an issue! Please provide as much detail as possible.
  
  - type: input
    id: title
    attributes:
      label: Add a title
      description: A brief title for your issue
      placeholder: Title
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Add a description
      description: Provide details about your issue
      placeholder: Type your description here...
    validations:
      required: false
