"""Render the structured memory store into memU's markdown "memory file system".

Everything an agent learns first becomes a **multimodal description** (the
modality-agnostic text/caption produced by preprocessing every source). That
description is the single shared trunk; three independent *bypasses* then project
it into the navigable file tree described in the README:

    memory/
    ├── INDEX.md                     ← map of everything: folders, files, sources
    ├── MEMORY.md                    ← profile, preferences, goals, key events
    └── skill/
        └── <skill_name>/SKILL.md    ← one learned skill / tool pattern per folder

The three bypasses are siblings — none is upstream of another; each is a
different aggregation of the same descriptions:

- ``INDEX.md``  : a table of contents (where to look before reading).
- ``MEMORY.md`` : the living memory, aggregated from folder (category) summaries.
- ``skill/**``  : skill memories broken out as standalone documents.

This layer is read-only against the database and never mutates memory records.
A sidecar manifest (``.memufs_manifest.json``) records the content hash of every
artifact this exporter owns, so each export only rewrites files whose rendered
content actually changed (diff detection) — no database schema change required.
Rendered content avoids volatile values (e.g. "now" timestamps) so re-exporting
an unchanged store is detected as a no-op.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from memu.database.interfaces import Database
    from memu.database.models import MemoryCategory, MemoryItem, Resource

MANIFEST_NAME = ".memufs_manifest.json"
SKILL_DIRNAME = "skill"
SKILL_FILENAME = "SKILL.md"
INDEX_FILENAME = "INDEX.md"
MEMORY_FILENAME = "MEMORY.md"
SKILL_MEMORY_TYPE = "skill"
_GENERATED_NOTICE = "<!-- Auto-generated by memU memory_fs. Do not edit by hand. -->"


@dataclass
class FileDescription:
    """A single source file's multimodal description (the shared trunk).

    Derived from a :class:`~memu.database.models.Resource`: ``caption`` is the
    text/caption produced by preprocessing, regardless of original modality.
    """

    url: str
    modality: str
    description: str
    resource_id: str


@dataclass
class ExportResult:
    """Outcome of a single export pass."""

    output_dir: str
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.written or self.removed)

    def to_dict(self) -> dict[str, Any]:
        return {
            "output_dir": self.output_dir,
            "changed": self.changed,
            "written": sorted(self.written),
            "unchanged": sorted(self.unchanged),
            "removed": sorted(self.removed),
        }


def slugify(name: str) -> str:
    """Turn a name into a filesystem-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "untitled"


def _content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


class MemoryFileExporter:
    """Render a :class:`~memu.database.interfaces.Database` into the markdown tree.

    The exporter is stateless apart from the on-disk manifest, so a single
    instance can be reused across scopes/exports. Callers are responsible for
    serializing concurrent exports that target the same ``output_dir``.
    """

    def __init__(self, output_dir: str) -> None:
        self.output_dir = pathlib.Path(output_dir)

    def export(
        self,
        database: Database,
        *,
        where: Mapping[str, Any] | None = None,
        memory_body: str | None = None,
        skills: dict[str, str] | None = None,
    ) -> ExportResult:
        """Render the (optionally scoped) store and write only changed artifacts.

        ``memory_body`` and ``skills`` are optional synthesized overrides (e.g.
        produced by :class:`~memu.memory_fs.synthesizer.MemorySynthesizer`). When
        provided they replace the deterministic, database-derived rendering of
        ``MEMORY.md`` / the ``skill/`` tree; ``INDEX.md`` is always deterministic.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        scope = dict(where) if where else None

        categories = list(database.memory_category_repo.list_categories(where=scope).values())
        resources = list(database.resource_repo.list_resources(where=scope).values())
        items = list(database.memory_item_repo.list_items(where=scope).values())

        # The shared trunk: one multimodal description per source file.
        descriptions = self._build_descriptions(resources)

        if skills is not None:
            skill_artifacts = {
                f"{SKILL_DIRNAME}/{slug}/{SKILL_FILENAME}": self._skill_document(body)
                for slug, body in skills.items()
            }
        else:
            skill_artifacts = self._skill_bypass(items)
        skill_slugs = sorted(rel.split("/")[1] for rel in skill_artifacts)

        body = memory_body if memory_body is not None else self._memory_body(categories)

        artifacts: dict[str, str] = {}
        artifacts.update(skill_artifacts)
        artifacts[MEMORY_FILENAME] = self._memory_document(body)
        artifacts[INDEX_FILENAME] = self._index_bypass(categories, descriptions, skill_slugs, items, database=database)

        return self._sync(artifacts)

    # -- trunk -------------------------------------------------------------

    @staticmethod
    def _build_descriptions(resources: list[Resource]) -> list[FileDescription]:
        descriptions: list[FileDescription] = []
        for resource in sorted(resources, key=lambda r: (r.url, r.id)):
            descriptions.append(
                FileDescription(
                    url=resource.url,
                    modality=resource.modality,
                    description=" ".join((resource.caption or "").split()),
                    resource_id=resource.id,
                )
            )
        return descriptions

    # -- bypass: SKILL -----------------------------------------------------

    def _skill_bypass(self, items: list[MemoryItem]) -> dict[str, str]:
        """Break out skill memories as standalone ``skill/<name>/SKILL.md`` docs."""
        skills = sorted(
            (item for item in items if item.memory_type == SKILL_MEMORY_TYPE and (item.summary or "").strip()),
            key=lambda i: (i.created_at, i.id),
        )
        artifacts: dict[str, str] = {}
        used: dict[str, int] = {}
        for item in skills:
            body = (item.summary or "").strip()
            base = self._skill_name(body, fallback=f"skill-{item.id[:6]}")
            count = used.get(base, 0)
            slug = base if count == 0 else f"{base}-{count + 1}"
            used[base] = count + 1
            rel_path = f"{SKILL_DIRNAME}/{slug}/{SKILL_FILENAME}"
            artifacts[rel_path] = self._skill_document(body)
        return artifacts

    @staticmethod
    def _skill_document(body: str) -> str:
        return f"{_GENERATED_NOTICE}\n\n{body.strip()}\n"

    @staticmethod
    def _skill_name(body: str, *, fallback: str) -> str:
        """Derive a skill folder slug from frontmatter ``name:`` or first heading."""
        if body.startswith("---"):
            end = body.find("\n---", 3)
            front = body[3:end] if end != -1 else ""
            match = re.search(r"^\s*name:\s*(.+)$", front, re.MULTILINE)
            if match:
                return slugify(match.group(1))
        heading = re.search(r"^#+\s*(.+)$", body, re.MULTILINE)
        if heading:
            return slugify(heading.group(1))
        return slugify(fallback)

    # -- bypass: MEMORY ----------------------------------------------------

    @staticmethod
    def _memory_document(body: str) -> str:
        body = body.strip() or "_No memory yet._"
        return f"# Memory\n\n{_GENERATED_NOTICE}\n\n{body}\n"

    def _memory_body(self, categories: list[MemoryCategory]) -> str:
        """The living memory body: folder (category) summaries aggregated."""
        if not categories:
            return ""
        sections: list[str] = []
        for category in sorted(categories, key=lambda c: (c.name.lower(), c.id)):
            description = self._inline((category.description or "").strip())
            summary = (category.summary or "").strip()
            block = [f"## {category.name}"]
            if description:
                block.append(f"_{description}_")
            block.append("")
            block.append(summary or "_No summary yet._")
            sections.append("\n".join(block))
        return "\n\n".join(sections)

    # -- bypass: INDEX -----------------------------------------------------

    def _index_bypass(
        self,
        categories: list[MemoryCategory],
        descriptions: list[FileDescription],
        skill_slugs: list[str],
        items: list[MemoryItem],
        *,
        database: Database,
    ) -> str:
        """Table of contents: where folders, skills, and sources live."""
        counts = self._item_counts_per_category(items, database=database)
        lines = ["# Index", "", _GENERATED_NOTICE, ""]

        lines += ["## Folders", ""]
        if categories:
            for category in sorted(categories, key=lambda c: (c.name.lower(), c.id)):
                description = self._inline((category.description or "").strip())
                count = counts.get(category.id, 0)
                suffix = f" — {description}" if description else ""
                lines.append(f"- **{category.name}**{suffix} ({count} items) → [{MEMORY_FILENAME}](./{MEMORY_FILENAME})")
        else:
            lines.append("_No folders yet._")
        lines.append("")

        lines += ["## Skills", ""]
        if skill_slugs:
            for slug in skill_slugs:
                rel = f"{SKILL_DIRNAME}/{slug}/{SKILL_FILENAME}"
                lines.append(f"- [{slug}](./{rel})")
        else:
            lines.append("_No skills yet._")
        lines.append("")

        lines += ["## Sources", ""]
        if descriptions:
            for desc in descriptions:
                text = desc.description or "_No description._"
                lines.append(f"- `{desc.url}` ({desc.modality}) — {text}")
        else:
            lines.append("_No source files yet._")
        lines.append("")
        return "\n".join(lines)

    # -- shared helpers ----------------------------------------------------

    @staticmethod
    def _item_counts_per_category(items: list[MemoryItem], *, database: Database) -> dict[str, int]:
        in_scope_ids = {item.id for item in items}
        counts: dict[str, int] = {}
        relations = getattr(database, "relations", None) or []
        for relation in relations:
            if relation.item_id in in_scope_ids:
                counts[relation.category_id] = counts.get(relation.category_id, 0) + 1
        return counts

    @staticmethod
    def _inline(text: str) -> str:
        """Collapse a value to a single safe line."""
        return " ".join(text.split())

    # -- diff / write ------------------------------------------------------

    def _sync(self, artifacts: dict[str, str]) -> ExportResult:
        manifest = self._load_manifest()
        result = ExportResult(output_dir=str(self.output_dir))
        new_manifest: dict[str, str] = {}

        for rel_path, content in artifacts.items():
            digest = _content_hash(content)
            new_manifest[rel_path] = digest
            target = self.output_dir / rel_path
            if manifest.get(rel_path) == digest and target.exists():
                result.unchanged.append(rel_path)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            result.written.append(rel_path)

        for rel_path in manifest:
            if rel_path in new_manifest:
                continue
            stale = self.output_dir / rel_path
            if stale.exists():
                stale.unlink()
            self._prune_empty_dirs(stale.parent)
            result.removed.append(rel_path)

        self._save_manifest(new_manifest)
        return result

    def _prune_empty_dirs(self, directory: pathlib.Path) -> None:
        """Remove now-empty directories created for nested artifacts (e.g. skill/<name>)."""
        root = self.output_dir.resolve()
        current = directory
        while current.resolve() != root and root in current.resolve().parents:
            try:
                next(current.iterdir())
            except StopIteration:
                current.rmdir()
                current = current.parent
            except OSError:
                break
            else:
                break

    # -- reading existing artifacts (for incremental update) ---------------

    def artifacts_exist(self) -> bool:
        """Whether a prior memory tree is already present (init vs update)."""
        return (self.output_dir / MEMORY_FILENAME).exists()

    def read_memory_body(self) -> str:
        """Read MEMORY.md and strip the heading/notice, returning just the body."""
        path = self.output_dir / MEMORY_FILENAME
        if not path.exists():
            return ""
        return self._strip_chrome(path.read_text(encoding="utf-8"), drop_heading="# Memory")

    def read_skills(self) -> dict[str, str]:
        """Read existing ``skill/<slug>/SKILL.md`` bodies keyed by slug."""
        skills: dict[str, str] = {}
        skill_root = self.output_dir / SKILL_DIRNAME
        if not skill_root.is_dir():
            return skills
        for child in sorted(skill_root.iterdir()):
            doc = child / SKILL_FILENAME
            if child.is_dir() and doc.exists():
                skills[child.name] = self._strip_chrome(doc.read_text(encoding="utf-8"))
        return skills

    @staticmethod
    def _strip_chrome(text: str, *, drop_heading: str | None = None) -> str:
        lines = text.splitlines()
        kept = [
            line
            for line in lines
            if line.strip() != _GENERATED_NOTICE and (drop_heading is None or line.strip() != drop_heading)
        ]
        return "\n".join(kept).strip()

    def _load_manifest(self) -> dict[str, str]:
        manifest_path = self.output_dir / MANIFEST_NAME
        if not manifest_path.exists():
            return {}
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
        if not isinstance(data, dict):
            return {}
        return {str(key): str(value) for key, value in data.items()}

    def _save_manifest(self, manifest: dict[str, str]) -> None:
        manifest_path = self.output_dir / MANIFEST_NAME
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")


__all__ = ["ExportResult", "FileDescription", "MemoryFileExporter", "slugify"]
