"""Render the structured memory store into a browsable markdown "memory file system".

This layer is purely additive and read-only against the database: it never mutates
memory records. It walks the existing folders (`MemoryCategory`), files
(`MemoryItem`), and source artifacts (`Resource`) and renders them into markdown
files on disk:

- ``MEMORY.md``           — top-level overview of all folders (categories).
- ``index.md``            — source-file description index (one entry per resource).
- ``skill.md``            — standalone aggregation of skill-type memories.
- ``categories/<slug>.md``— per-folder summary file (e.g. ``preferences.md``).

A sidecar manifest (``.memufs_manifest.json``) records the content hash of every
artifact this exporter owns, so each export only rewrites files whose rendered
content actually changed (diff detection). No database schema change is required.

Rendered content intentionally avoids volatile values (e.g. "now" timestamps) so
that re-exporting an unchanged store produces byte-identical output and is detected
as a no-op.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from memu.database.interfaces import Database
    from memu.database.models import MemoryCategory, MemoryItem, Resource

MANIFEST_NAME = ".memufs_manifest.json"
CATEGORIES_DIRNAME = "categories"
SKILL_MEMORY_TYPE = "skill"
_GENERATED_NOTICE = "<!-- Auto-generated by memU memory_fs. Do not edit by hand. -->"


@dataclass
class ExportResult:
    """Outcome of a single export pass."""

    output_dir: str
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.written or self.removed)

    def to_dict(self) -> dict[str, Any]:
        return {
            "output_dir": self.output_dir,
            "changed": self.changed,
            "written": sorted(self.written),
            "unchanged": sorted(self.unchanged),
            "removed": sorted(self.removed),
        }


def slugify(name: str) -> str:
    """Turn a category name into a filesystem-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "untitled"


def _content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


class MemoryFileExporter:
    """Render a :class:`~memu.database.interfaces.Database` into markdown artifacts.

    The exporter is stateless apart from the on-disk manifest, so a single instance
    can be reused across scopes/exports. Callers are responsible for serializing
    concurrent exports that target the same ``output_dir``.
    """

    def __init__(self, output_dir: str) -> None:
        self.output_dir = pathlib.Path(output_dir)

    def export(self, database: Database, *, where: Mapping[str, Any] | None = None) -> ExportResult:
        """Render the (optionally scoped) store and write only changed artifacts."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        scope = dict(where) if where else None

        categories = list(database.memory_category_repo.list_categories(where=scope).values())
        resources = list(database.resource_repo.list_resources(where=scope).values())
        items = list(database.memory_item_repo.list_items(where=scope).values())

        artifacts = self._render(categories, resources, items, database=database)
        return self._sync(artifacts)

    def _render(
        self,
        categories: list[MemoryCategory],
        resources: list[Resource],
        items: list[MemoryItem],
        *,
        database: Database,
    ) -> dict[str, str]:
        artifacts: dict[str, str] = {}

        slug_by_category = self._assign_slugs(categories)
        item_counts = self._item_counts_per_category(items, database=database)

        for category in categories:
            rel_path = f"{CATEGORIES_DIRNAME}/{slug_by_category[category.id]}.md"
            artifacts[rel_path] = self._render_category(category)

        artifacts["MEMORY.md"] = self._render_overview(categories, slug_by_category, item_counts)
        artifacts["index.md"] = self._render_index(resources)

        skill_doc = self._render_skills(items)
        if skill_doc is not None:
            artifacts["skill.md"] = skill_doc

        return artifacts

    @staticmethod
    def _assign_slugs(categories: list[MemoryCategory]) -> dict[str, str]:
        """Map each category id to a unique slug, disambiguating collisions."""
        used: dict[str, int] = {}
        result: dict[str, str] = {}
        for category in sorted(categories, key=lambda c: (c.name.lower(), c.id)):
            base = slugify(category.name)
            count = used.get(base, 0)
            slug = base if count == 0 else f"{base}-{count + 1}"
            used[base] = count + 1
            result[category.id] = slug
        return result

    @staticmethod
    def _item_counts_per_category(items: list[MemoryItem], *, database: Database) -> dict[str, int]:
        in_scope_ids = {item.id for item in items}
        counts: dict[str, int] = {}
        relations = getattr(database, "relations", None) or []
        for relation in relations:
            if relation.item_id in in_scope_ids:
                counts[relation.category_id] = counts.get(relation.category_id, 0) + 1
        return counts

    def _render_category(self, category: MemoryCategory) -> str:
        description = (category.description or "").strip()
        summary = (category.summary or "").strip()
        lines = [
            "---",
            f"name: {category.name}",
            f"description: {self._inline(description)}",
            f"updated_at: {category.updated_at.isoformat()}",
            "---",
            "",
            _GENERATED_NOTICE,
            "",
            summary or "_No summary yet._",
            "",
        ]
        return "\n".join(lines)

    def _render_overview(
        self,
        categories: list[MemoryCategory],
        slug_by_category: dict[str, str],
        item_counts: dict[str, int],
    ) -> str:
        lines = ["# Memory", "", _GENERATED_NOTICE, "", "## Folders", ""]
        if not categories:
            lines.append("_No memory folders yet._")
            lines.append("")
            return "\n".join(lines)
        for category in sorted(categories, key=lambda c: (c.name.lower(), c.id)):
            slug = slug_by_category[category.id]
            description = self._inline((category.description or "").strip())
            count = item_counts.get(category.id, 0)
            suffix = f" — {description}" if description else ""
            lines.append(f"- [{category.name}]({CATEGORIES_DIRNAME}/{slug}.md){suffix} ({count} items)")
        lines.append("")
        return "\n".join(lines)

    def _render_index(self, resources: list[Resource]) -> str:
        lines = ["# Index", "", _GENERATED_NOTICE, "", "## Source files", ""]
        if not resources:
            lines.append("_No source files yet._")
            lines.append("")
            return "\n".join(lines)
        for resource in sorted(resources, key=lambda r: (r.url, r.id)):
            description = self._inline((resource.caption or "").strip()) or "_No description._"
            lines.append(f"- `{resource.url}` ({resource.modality}) — {description}")
        lines.append("")
        return "\n".join(lines)

    def _render_skills(self, items: list[MemoryItem]) -> str | None:
        skills = sorted(
            (item for item in items if item.memory_type == SKILL_MEMORY_TYPE),
            key=lambda i: (i.created_at, i.id),
        )
        if not skills:
            return None
        blocks = [(item.summary or "").strip() for item in skills]
        blocks = [block for block in blocks if block]
        if not blocks:
            return None
        body = "\n\n---\n\n".join(blocks)
        return f"# Skills\n\n{_GENERATED_NOTICE}\n\n{body}\n"

    @staticmethod
    def _inline(text: str) -> str:
        """Collapse a value to a single safe line for frontmatter / list entries."""
        return " ".join(text.split())

    def _sync(self, artifacts: dict[str, str]) -> ExportResult:
        manifest = self._load_manifest()
        result = ExportResult(output_dir=str(self.output_dir))
        new_manifest: dict[str, str] = {}

        for rel_path, content in artifacts.items():
            digest = _content_hash(content)
            new_manifest[rel_path] = digest
            target = self.output_dir / rel_path
            if manifest.get(rel_path) == digest and target.exists():
                result.unchanged.append(rel_path)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            result.written.append(rel_path)

        for rel_path in manifest:
            if rel_path in new_manifest:
                continue
            stale = self.output_dir / rel_path
            if stale.exists():
                stale.unlink()
            result.removed.append(rel_path)

        self._save_manifest(new_manifest)
        return result

    def _load_manifest(self) -> dict[str, str]:
        manifest_path = self.output_dir / MANIFEST_NAME
        if not manifest_path.exists():
            return {}
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
        if not isinstance(data, dict):
            return {}
        return {str(key): str(value) for key, value in data.items()}

    def _save_manifest(self, manifest: dict[str, str]) -> None:
        manifest_path = self.output_dir / MANIFEST_NAME
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")


__all__ = ["ExportResult", "MemoryFileExporter", "slugify"]
